---
title: "Ejercicios"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Ejericio 1
Se definen las matrices A y B. Hacer los cálculos manuales y posteriormente usar R
o el paquete que ustedes quieran para encontrar las siguientes matrices, si es posible. Si no, 
decir porqué 

```{r}
a <- matrix(data=c(7,2,5,1,3,8),nrow=2,ncol=3)
b <- matrix(data=c(11,12,-7,0,8,9),nrow=2,ncol=3)
a_t <- t(a) #transponemos la matriz a 
a - b # resta de matrices 
# a%*%b #producto de matrices a con b, (non-conformable arguments)
a_t%*%a 
a%*%a_t  
a+b
a_t%*%b
b_t <- t(b)
a%*%b_t
a_2 <- 17.3*a
b_2 <- (1/19)*b
b_2
```
# Ejercicio 2 

```{r pressure, echo=FALSE}
install.packages("dplyr",repos="http://cran.us.r-project.org")
library(dplyr)
tabla <- read.table("T1-6.DAT")
colnames(tabla) <-c("x1","x2","x3","x4","x5","x6")
grupo1 <-subset(tabla,x6=="0",select = -x6)
grupo2 <-subset(tabla,x6=="1",select = -x6)

#gráfica de dispersión 
plot(grupo2$x2,grupo2$x4, main ="Gráfica de dispersión", xlab = "respuesta a estímulo S1",ylab="respuesta a estímulo S2", pch=19,frame=FALSE)
abline(lm(x4~x2,data=grupo2),col="red")

```
#Ejercicio 2: indicadores estadísticos para el grupo 1 y 2
```{r}
#grupo 1
grupo1 <-as.matrix(grupo1)
n <- nrow(grupo1)
uno <- rep(1,n)
v_medias <- t(grupo1) %*% uno/n
H <- diag(n) - uno%*% t(uno)/n 
S <- round(t(grupo1) %*% H %*% grupo1/(n-1),2)
R <- cor(grupo1)


#grupo2
grupo2 <-as.matrix(grupo2)
n <- nrow(grupo2)
uno <- rep(1,n)
v_medias <- t(grupo2) %*% uno/n
H <- diag(n) - uno%*% t(uno)/n 
S <- round(t(grupo2) %*% H %*% grupo2/(n-1),2)
R <- cor(grupo2)
```
#Matrices de gráficas de dispersión
```{r}
pairs(grupo2[,],pch=19,lower.panel = panel.smooth,upper.panel=panel.smooth, main="Información del grupo 1 -- Esclerosis")
pairs(grupo1[,],pch=19,lower.panel = panel.smooth,upper.panel=panel.smooth, main="Información del grupo 2 -- sin Esclerosis")
```
#Ejercicio 3
```{r}
# a) Obtención del vector de medias, la matriz A y la matriz de covarianza muestral insesgada
library(datasets)
data("iris3")
flores <-as.data.frame(iris3)
setosa <-as.matrix(subset(flores,select = -c(5:12)))
m <- nrow(setosa)
uno <- rep(1,m)
v_medias_setosa <-t(setosa) %*% uno/m
H <- diag(m) - uno%*% t(uno)/m 
A <- round(t(setosa) %*% H %*% setosa,2)
S_x <- (1/49)*A
```
```{r}
# b) Obtención de los eigenvalores y eigenvectores de S
lista <-eigen(S_x)
e_valores <-as.vector(lista[[1]])
U <-as.matrix(lista[[2]])
L=diag(e_valores)
S <-U%*%L%*%t(U)
I4 <- t(U)%*%U
I4_2 <- U%*%t(U)

# c) Matriz de gráficas de dispersión
pairs(iris[,1:4],main="Característica númericas -- 3 especies de flores", pch=21,bg=c("blue","gray","green3")[iris$Species], oma=c(4,4,6,12))
par(xpd=TRUE)
legend(0.85,0.6, as.vector(unique(iris$Species)),fill=c("blue","gray","green3"))


```

# Ejercicio 4
```{r}
matriz_identidad <-diag(ncol(setosa))
C <- cbind(matriz_identidad,c(0,0,1,1))
Y <- setosa%*%C
s <- nrow(Y)
uno <- rep(1,s)
H <- diag(s) - uno%*% t(uno)/s 
A <- round(t(Y) %*% H %*% Y,2)
S_y <- (1/49)*A
S_y_c <- t(C)%*%S_x%*%C
```

